version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: qwertttyyy/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    image: qwertttyyy/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: nginx:1.22.1
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
